threescale: true
threescale_version: 2.4.0.GA
threescale_template: https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/{{threescale_version}}/amp/amp.yml
amq: true
amq_version: '7.2'
amq_release_tag: 72-1.1.GA
amq_template_short_tag: '72'
che: true
che_version: 6.9.0
che_template: https://raw.githubusercontent.com/eclipse/che/{{che_version}}/deploy/openshift/templates/che-server-template.yaml
che_postgres_template: https://github.com/eclipse/che/blob/{{che_version}}/deploy/openshift/templates/multi/postgres-template.yaml
enmasse: true
enmasse_version: beta
enmasse_download_url: https://github.com/EnMasseProject/enmasse/releases/download/{{ enmasse_version }}/enmasse-{{ enmasse_version }}.tgz
is_productised_version: true
enmasse_productised_download_url: https://access.redhat.com/sites/default/files/announcements/install_and_examples_1.zip
fuse: true
fuse_release_tag: application-templates-2.1.fuse-720018-redhat-00001
fuse_version: '7.2'
fuse_online: true
fuse_online_release_tag: '1.5'
fuse_online_operator_resources: https://raw.githubusercontent.com/syndesisio/fuse-online-install/{{fuse_online_release_tag}}/resources/fuse-online-operator.yml
launcher: true
launcher_backend_image_tag: b006e49
launcher_frontend_image_tag: a00064f
launcher_version: 7224e235226ffa42135f148bacc409e9f7f402e4
launcher_template: https://raw.githubusercontent.com/fabric8-launcher/launcher-openshift-templates/{{launcher_version}}/openshift/launcher-template.yaml
rh_sso_version: 7.2.2.GA
rh_sso_opertor_release_tag: 0.0.2
rh_sso_operator_resources: https://raw.githubusercontent.com/integr8ly/keycloak-operator/{{rh_sso_opertor_release_tag}}/deploy/
gitea: true
gitea_version: 1.6.0
gitea_operator_release_tag: v0.0.2
gitea_operator_resources: https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_operator_release_tag}}/deploy/operator.yaml
webapp: true
webapp_version: 1.0.0
webapp_operator_release_tag: master
webapp_operator_resources: https://raw.githubusercontent.com/integr8ly/tutorial-web-app-operator/{{webapp_operator_release_tag}}/deploy/
apicurito: true
apicurito_version: 0.2.18.Final
nexus: true
nexus_version: 2.14.11-01
